name: FASTAPI CI/CD - DEPLOYMENT

# 觸發條件
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# 執行一項或多項任務
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

#    # 建立環境
#    - name: Install Dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r ./requirements.txt

#    # 運行測試
#    - name: Run Tests
#      run: |
#        cd flask
#        bash test.sh

    # 遠端部署
    - name: CD
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          if cd /home/lighthouse/MumuMemoServer; then git pull git@github.com:MumuMemo/Mumu-Memo-Server.git; else git clone https://server/repo /home/lighthouse/MumuMemoServer; fi
          cd /home/lighthouse/MumuMemoServer
          git pull git@github.com:MumuMemo/Mumu-Memo-Server.git
          docker-compose up --build -d